# Generated by Django 4.1.2 on 2024-05-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('equation', models.CharField(max_length=255)),
                ('solution', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
            ],
        ),
    ]
