# Generated by Django 4.1.2 on 2024-06-04 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equation_solver_service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equation',
            old_name='user_id',
            new_name='user',
        ),
    ]
